force-app/main/default/objects/Planned_Sales__c/Planned_Sales__c.object-meta.xml
<CustomObject>
    <label>Planned Sales</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Planned Sales</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planned Sales</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Planned_Sales__c/fields/Planned_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Planned_Total_Amount__c</fullName>
    <description>Currency field representing the expected revenue from these planned sales.</description>
    <label>Planned Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Planned_Sales__c/fields/Total_Amount_Earned__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Earned__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Currency field that will be populated automatically based on sales records.</description>
    <label>Total Amount Earned</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/MonthlySalesCheckNotificationQueueable.cls
/**
 * @description       : 
 * @author            : Nazar Voinarovych
 * @group             : 
 * @last modified on  : 11-06-2024
 * @last modified by  : Nazar Voinarovych
**/
public class MonthlySalesCheckNotificationQueueable implements Queueable{

    private List<Planned_Sales__c> underperfomancePlannedSales;

    public MonthlySalesCheckNotificationQueueable(List<Planned_Sales__c> plannedSales){
        this.underperfomancePlannedSales=plannedSales;
    }
    
    public void execute(QueueableContext context){
        List<User> systemAdministrators=[SELECT Id,Email,Profile.Name FROM USER WHERE Profile.Name='System Administrator'];
        List<String> adminEmails=new List<String>();

        if(!systemAdministrators.isEmpty()){
            for(User user:systemAdministrators){
                adminEmails.add(user.Email);
            }
        }
        String emailBody='Underperfomance Planned Sales records:';

        for(Planned_Sales__c plannedSale:underperfomancePlannedSales){
            emailBody+='Record Id: '+plannedSale.Id+'Total Amount Earned: '+plannedSale.Total_Amount_Earned__c+'Planned Total Amount: '+plannedSale.Planned_Total_Amount__c+'\n';
        }
        Messaging.SingleEmailMessage email=new Messaging.SingleEmailMessage();
        email.setToAddresses(adminEmails);
        email.setSubject('Underperfoming Planned Sales records');
        email.setPlainTextBody(emailBody);

        Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});//sent emails

    }

}