force-app/main/default/objects/Planned_Sales__c/Planned_Sales__c.object-meta.xml
<CustomObject>
    <label>Planned Sales</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Planned Sales</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planned Sales</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Planned_Sales__c/fields/Planned_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Planned_Total_Amount__c</fullName>
    <description>Currency field representing the expected revenue from these planned sales.</description>
    <label>Planned Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Planned_Sales__c/fields/Total_Amount_Earned__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Earned__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Currency field that will be populated automatically based on sales records.</description>
    <label>Total Amount Earned</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Planned_Sales__c/fields/Underperfoming__c.field-meta.xml
<CustomField>
    <fullName>Underperfoming__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Underperfoming</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/MonthlySalesCheckScheduleTest.cls
/**
 * @description       : 
 * @author            : Nazar Voinarovych
 * @group             : 
 * @last modified on  : 11-06-2024
 * @last modified by  : Nazar Voinarovych
**/
@isTest
public with sharing class MonthlySalesCheckScheduleTest {
    @TestSetup
    static void makeData(){
        Trigger_Control__c plannedSalesTriggerControl=TestDataFactory.createPlannedSalesTriggerControl();
        insert plannedSalesTriggerControl;

        List<Planned_Sales__c> plannedSales=TestDataFactory.createPlannedSales(False);

        for(Planned_Sales__c plannedSale:plannedSales){
            plannedSale.Total_Amount_Earned__c=100;
            plannedSale.Planned_Total_Amount__c=200;
            plannedSale.Underperfoming__c=true;
        }
        insert plannedSales;
    }
    @isTest
    private static void testMonthlySalesCheckSchedule(){
        String cronExpression='0 0 0 1 * ? ';
        Test.startTest();
        String jobId=System.schedule('Monthly Planned Sales Check Test', cronExpression, new MonthlySalesCheckSchedule());
        Test.stopTest();

        CronTrigger cron=[SELECT Id,CronExpression,State FROM CronTrigger WHERE Id=:jobId];
        Assert.areEqual('WAITING', cron.State);

    }
}