force-app/main/default/objects/Planned_Sales__c/Planned_Sales__c.object-meta.xml
<CustomObject>
    <label>Planned Sales</label>
    <nameField>
        <displayFormat>PS-{000000}</displayFormat>
        <label>Planned Sales</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Planned Sales</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Planned_Sales__c/fields/isPlannedTotalAmountGreaterThanTotalAmou__c.field-meta.xml
<CustomField>
    <fullName>isPlannedTotalAmountGreaterThanTotalAmou__c</fullName>
    <formula>Total_Amount_Earned__c  &lt;  Planned_Total_Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>isPlannedTotalAmountGreaterThanTotalAmou</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Planned_Sales__c/fields/Planned_Total_Amount__c.field-meta.xml
<CustomField>
    <fullName>Planned_Total_Amount__c</fullName>
    <description>Currency field representing the expected revenue from these planned sales.</description>
    <label>Planned Total Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Planned_Sales__c/fields/Total_Amount_Earned__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_Earned__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Currency field that will be populated automatically based on sales records.</description>
    <label>Total Amount Earned</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Planned_Sales__c/fields/Underperfoming__c.field-meta.xml
<CustomField>
    <fullName>Underperfoming__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Underperfoming</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/MonthlySalesCheckBatch.cls
/**
 * @description       : 
 * @author            : Nazar Voinarovych
 * @group             : 
 * @last modified on  : 11-07-2024
 * @last modified by  : Nazar Voinarovych
**/
public with sharing class MonthlySalesCheckBatch implements Database.Batchable<sObject>{
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        // collect the batches of records or objects to be passed to execute
        return Database.getQueryLocator('SELECT Id,Total_Amount_Earned__c,Planned_Total_Amount__c,isPlannedTotalAmountGreaterThanTotalAmou__c FROM Planned_Sales__c WHERE isPlannedTotalAmountGreaterThanTotalAmou__c=true');
    }
    public void execute(Database.BatchableContext bc, List<SObject> records){
        // process each batch of records
        List<Planned_Sales__c> plannedSales=(List<Planned_Sales__c>) records;

        List<Planned_Sales__c> filteredPlannedSales=new List<Planned_Sales__c>();

        for(Planned_Sales__c plannedSale:plannedSales){
            if(plannedSale.Total_Amount_Earned__c<plannedSale.Planned_Total_Amount__c){
                plannedSale.Underperfoming__c=true;
                filteredPlannedSales.add(plannedSale);
            }
        }
        if(!filteredPlannedSales.isEmpty()){
            update filteredPlannedSales;
            System.enqueueJob(new MonthlySalesCheckNotificationQueueable(filteredPlannedSales));
        }
    }
    public void finish(Database.BatchableContext bc){
        // execute any post-processing operations
        system.debug('MonthlySalesChekBatch finish:'+bc);
    }
}